server:
  error:
    path: /error

spring:
  profiles:
    active:
      - dev
  config:
    import: file:.env[.properties]
  application:
    name: tournament-management
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway: # TODO remove & properly set up Flyway
    enabled: false

---

# DEV profile

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    pjatk.s18617: debug
    org.springframework: debug
    org.hibernate: debug
    org.hibernate.orm.jdbc.bind: trace

---

# PROD profile

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate