server:
  error:
    path: /error

spring:
  profiles:
    active:
      - dev
      - flyway-clean
  config:
    import: optional:file:.env[.properties]
  application:
    name: tournament-management
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true

---

# DEV profile

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    pjatk.s18617: debug
    org.springframework: debug
    org.hibernate: debug
    org.hibernate.orm.jdbc.bind: trace

---

# FLYWAY-CLEAN profile
# drops all objects in configured schema (see FlywayCleanupOnShutdown class in config package)
# used mainly for experimenting with migrations

spring:
  config:
    activate:
      # disabled when "prod" profile is enabled regardless of the other profiles
      on-profile: flyway-clean & !prod
  flyway:
    clean-disabled: false

---

# PROD profile

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate